import type { CaseContent } from '../../contracts/types'

// The Missing A$48,000, shared by Mei L. (Finance & Treasury). Individual mode only.
// The source gives the task and its figures (ledger A$1,248,000, bank statement A$1,200,000), the
// three starting materials, the four materials the learner can request, the designed facts (A$30,000
// is settlement timing; the other A$18,000 is a record duplicated by an import, which affects the
// report but is not money lost), the core conflict (explaining part of the difference is not solving
// the whole problem), the submission, the three Team Lead observations and the follow-up. Every fact
// beyond those, and all wording not translated from the source, is a DRAFT: to be confirmed. Every
// name in it is fictional.
// In a material body, '\n' is a line break and lines with '|' are rows of a small table (first row: header).
export const CASE: CaseContent = {
  id: 'missing-48000',
  // The source's task, translated (not a draft).
  background:
    'The internal ledger shows A$1,248,000 and the bank statement shows A$1,200,000, and the reporting deadline is close.',
  brief:
    'The internal ledger shows A$1,248,000 and the bank statement shows A$1,200,000, and the reporting deadline is close. Explain the difference and recommend how to handle it.',
  // m1–m3 open at the start; m4–m7 unlock by request (r1 → m4 … r4 → m7). Titles are the source's
  // material names, as in library.ts. Figures agree across materials: A$1,248,000 − A$30,000 (card
  // sales of 30 June, due in the bank on 2 July) − A$18,000 (the Pellham receipt, loaded twice as
  // L-5530 and L-5531) = A$1,200,000. The report is due on 1 July at 15:00, before the A$30,000 arrives.
  // Every body, source, date and scope is a DRAFT: to be confirmed.
  materials: [
    {
      id: 'm1',
      title: 'Ledger and bank statement summaries',
      visibility: 'start',
      body: "Account: main operating account, AUD.\nSource | Balance at 30 June\nInternal ledger | A$1,248,000\nBank statement | A$1,200,000\nDifference | A$48,000, ledger higher\nThe June month-end report is due to the Financial Controller by 1 July, 15:00.\nAny correction to the ledger needs the Financial Controller's approval.",
      source: 'Finance system and bank statement, June month-end',
      date: '1 July, 08:30',
      scope: 'Balances only; not which items make up the difference',
    },
    {
      id: 'm2',
      title: 'When the statement was generated',
      visibility: 'start',
      body: 'Bank statement file: generated by the bank on 30 June at 18:05.\nInternal ledger: closed for June on 30 June at 23:59.',
      source: 'Statement file details and the ledger close log',
      date: '30 June',
      scope: 'When each was produced; not what each includes',
    },
    {
      id: 'm3',
      title: 'Pending transactions list',
      visibility: 'start',
      body: "Ledger items with no match on the bank statement. Every other June item matched.\nRef | Ledger date | Description | Amount\nP-101 | 30 June | Card sales, 30 June | A$30,000\nP-102 | 29 June | Receipt, Pellham Fixtures, invoice 4471 | A$18,000\nTotal not on the statement: A$48,000.\nMonth-end team, 1 July, 08:40: \"Probably timing. These usually clear in a few days.\"\nTeam chat, 1 July, 08:50: \"Pellham's A$18,000 isn't in the bank. Have we lost it?\"",
      source: 'Matching run, 1 July, 08:30, with notes from the month-end team and the team chat',
      date: '1 July, 08:50',
      scope: 'What did not match; not why',
    },
    // The source: A$30,000 is about settlement timing.
    {
      id: 'm4',
      title: 'Settlement times',
      visibility: 'request',
      body: 'Card sales are recorded in the ledger as cash on the day of the sale.\nThe card processor pays them into the bank two business days later.\nCard sales of 30 June, A$30,000: due in the bank on 2 July.\nBank feed at 1 July, 09:30: not received yet, as expected.\nThis year, every card payment has arrived on its due date.',
      source: 'Treasury settlement schedule and bank feed',
      date: '1 July, 09:30',
      scope: 'Card sales only; not other receipts',
    },
    // The source: the other A$18,000 is a duplicated record. It affects the report; no money is lost.
    {
      id: 'm5',
      title: 'Duplicate record check',
      visibility: 'request',
      body: 'Search: June ledger entries with the same reference, amount and date. Found: one pair.\nEntry | Ledger date | Reference | Amount | Matched to the bank?\nL-5530 | 29 June | Pellham Fixtures, invoice 4471 | A$18,000 | Yes, bank credit of 29 June\nL-5531 | 29 June | Pellham Fixtures, invoice 4471 | A$18,000 | No (this is P-102)\nThe bank statement shows one A$18,000 credit from Pellham Fixtures in June.\nInvoice 4471 is for A$18,000.',
      source: 'Ledger search, run by the finance team',
      date: '1 July, 10:00',
      scope: 'June, main operating account only',
    },
    {
      id: 'm6',
      title: 'Statement date range',
      visibility: 'request',
      body: "The statement covers what the bank posted from 1 June, 00:00 to 30 June, 16:00, the bank's cut-off.\nAnything the bank posts after the cut-off appears on the July statement.\nThe ledger's June runs from 1 June, 00:00 to 30 June, 23:59.\nBank postings between 16:00 and 23:59 on 30 June: none.",
      source: 'Bank statement notes',
      date: '30 June',
      scope: 'The June statement only',
    },
    {
      id: 'm7',
      title: 'Data import log',
      visibility: 'request',
      body: 'Import: bank receipts file for 29 June, loaded into the ledger.\nRun 1, 29 June, 14:02: stopped on a timeout after loading row 1 of 38, the Pellham receipt (L-5530).\nRun 2, 29 June, 14:20: started again from row 1 and loaded all 38 rows as L-5531 to L-5568. L-5531 is the Pellham receipt again.\nThe import does not check for rows already loaded.\nNo other file was re-run in June.\nThe receivables report reads the same ledger entries. It shows Pellham Fixtures as having paid A$36,000 against invoice 4471 for A$18,000.',
      source: 'Ledger import log, pulled by Engineering',
      date: '1 July, 10:30',
      scope: 'June imports into the ledger',
    },
  ],
  framePrompt: 'Part of the gap has an easy explanation. Does that explain all of it?', // DRAFT: to be confirmed (from the source's core conflict)
  constraints: [
    { label: 'Report due 1 July, 15:00', known: true }, // DRAFT: to be confirmed
    { label: 'Timing or error?', known: false }, // DRAFT: to be confirmed
    { label: 'Money lost?', known: false }, // DRAFT: to be confirmed
  ],
  // Every card comes from a start material (m1–m3); each is a DRAFT: to be confirmed.
  cards: [
    { id: 'c1', text: 'Ledger A$1,248,000; bank A$1,200,000', source: 'Balance summaries' },
    { id: 'c2', text: 'Statement generated 30 June, 18:05', source: 'Statement file' },
    { id: 'c3', text: 'Two items not on the statement, A$48,000', source: 'Pending list' },
    { id: 'c4', text: 'The A$30,000 is card sales still to arrive', source: 'Pending list description' },
    { id: 'c5', text: 'It’s all timing; it will clear', source: 'Month-end team' },
    { id: 'c6', text: 'Pellham’s A$18,000 is missing', source: 'Team chat' },
  ],
  // The source's four requestable materials. Hours and why lines are DRAFT: to be confirmed.
  // Together they take 3.5 h against a 3 h budget, so the learner has to choose.
  requests: [
    {
      id: 'r1',
      title: 'Settlement times',
      hours: 1,
      why: 'card sales may reach the bank later than the ledger records them',
      finding: {
        label: 'Settlement times',
        text: 'Card sales reach the bank two business days after the sale. The A$30,000 is due on 2 July and has not arrived yet.',
      },
      materialId: 'm4',
    },
    {
      id: 'r2',
      title: 'Duplicate record check',
      hours: 1,
      why: 'an unmatched receipt may be a second copy',
      finding: {
        label: 'Duplicate check',
        text: 'The Pellham receipt is in the ledger twice, as L-5530 and L-5531. The bank has it once.',
      },
      materialId: 'm5',
    },
    {
      id: 'r3',
      title: 'Statement date range',
      hours: 0.5,
      why: 'the statement may stop earlier than the ledger',
      finding: {
        label: 'Date range',
        text: 'The statement stops at 16:00 on 30 June. The bank posted nothing between then and midnight.',
      },
      materialId: 'm6',
    },
    {
      id: 'r4',
      title: 'Data import log',
      hours: 1,
      why: 'the log shows how a record got in',
      finding: {
        label: 'Import log',
        text: 'The 29 June import was re-run from the start, loading the Pellham receipt twice. Receivables now shows A$36,000 paid.',
      },
      materialId: 'm7',
    },
  ],
  timeBudgetHours: 3, // DRAFT: to be confirmed
  // A all timing, B each part with its own fix, C possible lost funds. DRAFT: to be confirmed
  options: [
    { id: 'A', label: 'Report it all as timing that will clear', tradeoff: 'Quick to write; treats the whole gap as one cause' },
    { id: 'B', label: 'Report each part, with a fix and a control', tradeoff: 'Every part needs its own evidence and owner' },
    { id: 'C', label: 'Report A$48,000 as possible lost funds', tradeoff: 'Nothing played down; starts a funds investigation' },
  ],
  // DRAFT: to be confirmed (titles follow the Japan case; questions and prompt are drafted)
  decisionPoints: [
    {
      id: 'dp1',
      step: 'define',
      title: 'Define the task',
      question: 'What must the note explain, and what may you decide yourself?',
      status: 'confirmed',
    },
    {
      id: 'dp2',
      step: 'examine',
      title: 'Sort the evidence',
      question: 'Which items are records, and which are guesses about the gap?',
      status: 'review',
      reviewPrompt: 'The team chat says Pellham’s A$18,000 is missing. Treat it as a guess to check, not a finding?',
    },
    {
      id: 'dp3',
      step: 'investigate',
      title: 'Close the gaps',
      question: 'What would show whether each part is timing, an error or a loss?',
      status: 'confirmed',
      chips: ['Settlement times', 'Duplicate record check', 'Statement date range', 'Data import log'],
    },
    {
      id: 'dp4',
      step: 'decide',
      title: 'Make the call',
      question: 'How do you report the A$48,000, and who fixes what?',
      status: 'confirmed',
    },
  ],
  skillIds: ['evidence', 'investigation', 'decision'], // matches library.ts
  // Mei's reference answers: a reference, not an answer key. Everything in senior is a
  // DRAFT: to be confirmed. It follows the source's three Team Lead observations.
  senior: {
    decision: 'B',
    why: 'A$30,000 is card sales due on 2 July; A$18,000 is one receipt loaded twice. Report each part, correct the duplicate with approval, and fix the import.',
    byPoint: {
      dp1: {
        answer:
          'Explain what makes up the A$48,000 by 15:00, keeping any real loss of money apart from errors in the records, and propose fixes. Correcting the ledger is the Financial Controller’s call.',
        reason:
          'A gap between the ledger and the bank can be timing, a recording error or a loss. The note must say which, for each part, and how sure we are.',
      },
      dp2: {
        answer:
          'Verified: the two balances, the statement time and the two unmatched items. Needs checking: that the A$30,000 is card sales still to arrive. Assumption: that it is all timing. Weak: that Pellham’s A$18,000 is missing.',
        reason:
          'The pending list shows what did not match, not why. The team’s two guesses point opposite ways, and neither rests on a record.',
      },
      dp3: {
        answer: 'Settlement times, the duplicate record check and the data import log: 3 of the 3 hours. Skip the statement date range.',
        reason:
          'Settlement times test the A$30,000. The duplicate check and the import log show whether the A$18,000 is a loss or a records error, and what else the error touched.',
      },
      dp4: {
        answer:
          'B: report A$30,000 as card sales due on 2 July, not yet received, and A$18,000 as one receipt loaded twice, with no money lost. Ask the Financial Controller to approve reversing L-5531, have Engineering make the import skip rows already loaded, and tell receivables not to refund Pellham the A$18,000 their report shows as overpaid.',
        reason:
          'Each part has its own evidence and its own fix. A would hide a records error behind timing; C would start a funds investigation for money that arrived. The A$30,000 stays open until it lands.',
      },
    },
    goal: 'Explain each part of the gap, keep money apart from records, and fix the cause',
    success: ['Every dollar of the A$48,000 accounted for', 'An import that cannot load the same row twice'],
    sort: {
      c1: 'verified',
      c2: 'verified',
      c3: 'verified',
      c4: 'needs-checking',
      c5: 'assumption',
      c6: 'weak',
    },
    requestIds: ['r1', 'r2', 'r4'], // 1 + 1 + 1 = 3 of the 3 hours
  },
  // DRAFT: to be confirmed
  outcome:
    'The A$30,000 arrived on 2 July as scheduled. The controller approved reversing the duplicate before the report went out, and the import got a check for rows already loaded later in July.',
  // The example: Alex first reads the unmatched receipt as lost money. The settlement times and the
  // duplicate check move them to B, and they say plainly that no money was lost. They skip the import
  // log, so the control stays vague, and they write 'None' under unresolved risks while the A$30,000
  // is still on its way: the gaps the review picks up. Everything in it is a DRAFT: to be confirmed.
  example: {
    juniorId: 'alex',
    initialPosition: {
      recommendation: 'C: report A$48,000 as possible lost funds',
      reason: 'The bank has A$48,000 less than the ledger, and Pellham’s A$18,000 is not on the statement.',
      confidence: 'low',
      question: 'Did Pellham’s A$18,000 ever reach the bank?',
    },
    goal: 'Find the missing A$48,000 before 15:00',
    success: ['The gap explained by the deadline', 'Any lost money found'],
    people: ['Financial Controller', 'Month-end team', 'Pellham Fixtures'],
    sort: {
      c1: 'verified',
      c2: 'verified',
      c3: 'verified',
      c4: 'needs-checking',
      c5: 'assumption',
      c6: 'verified',
    },
    sortReasons: {
      c1: 'Straight from the ledger and the statement.',
      c2: 'On the statement file.',
      c3: 'The matching run lists them.',
      c4: 'The description says card sales; nothing says when they arrive.',
      c5: 'A guess from experience.',
      c6: 'The pending list shows it is not on the statement.',
    },
    missing: ['When card sales reach the bank', 'Whether the Pellham receipt was recorded twice'],
    requestedIds: ['r1', 'r2', 'r3'], // 1 + 1 + 0.5 = 2.5 of the 3 hours
    requestIntents: {
      r1: 'Whether the A$30,000 is card sales still on their way',
      r2: 'Whether the Pellham receipt appears twice in the ledger',
      r3: 'Whether the statement stops earlier than the ledger',
    },
    decision: 'B',
    basedOn: ['Card sales due 2 July', 'Pellham receipt entered twice', 'Nothing posted after cut-off'],
    why: 'The A$30,000 is card sales that reach the bank two business days after the sale, and the A$18,000 is the same Pellham receipt entered twice in the ledger. The bank got Pellham’s money once, so nothing is lost; the ledger is overstated.',
    mainRisk: 'The same duplicate could happen at the next import',
    changeMind: 'If the card sales did not arrive on 2 July, I would treat the A$30,000 as missing',
    confidence: 'high',
    submission: {
      'make-up': 'A$30,000 of card sales from 30 June, and A$18,000 from a Pellham receipt entered twice. Total A$48,000.',
      evidence:
        'Settlement times: card sales reach the bank two business days later. Duplicate record check: L-5530 and L-5531 are the same receipt, and the bank has it once.',
      'open-risks': 'None. Both parts are explained.',
      'fix-owner': 'The finance team reverses L-5531, with the Financial Controller’s approval.',
      prevention: 'Check imports more carefully before month-end.',
    },
    whyChanged:
      'I started out thinking A$48,000 might be lost, because Pellham’s receipt was not on the statement. The settlement times showed the A$30,000 is card sales on their way, and the duplicate check showed the Pellham receipt was entered twice. So it is a records problem, not lost money.',
    // Stored without quote marks; the page adds them.
    note: 'I first read the unmatched receipt as missing money. It was the same receipt entered twice.',
  },
  // Sam's review of the example. Everything in it is a DRAFT: to be confirmed. The senior column
  // matches senior.goal, senior.sort, senior.requestIds and senior.decision.
  review: {
    managerId: 'sam',
    submittedWhen: 'today',
    minutes: 16,
    // In a row's text, ' → ' shows as the arrow icon (read as 'then').
    rows: [
      { label: 'Goal', junior: 'Find the missing A$48,000', senior: 'Explain each part; money vs records', match: 'differs' },
      { label: 'Evidence', junior: 'Team chat taken as proof', senior: 'Team chat is a guess', match: 'differs' },
      { label: 'Investigation', junior: 'Settlement → duplicates → range', senior: 'Settlement → duplicates → import log', match: 'differs' },
      { label: 'Decision', junior: 'B · Report each part', senior: 'B · Report each part', match: 'aligned' },
    ],
    blindSpots: ['Wrote "None" under unresolved risks while the A$30,000 was still on its way', 'Did not find how the duplicate got in, or what else it touched'],
    confirmQuestions: ['Should the note mark the A$30,000 as expected, not settled?', 'Is "check imports more carefully" a control anyone can act on?'],
    feedbackDraft:
      'Good work splitting the A$48,000 into two parts and saying plainly that no money was lost. Next time, list what is still unconfirmed, even when every part has an explanation.',
    nextFocus: ['evidence', 'investigation', 'decision'],
    nextFocusDefault: 'evidence',
    dimensions: [
      {
        id: 'goal',
        level: 'independent',
        note: 'Alex kept the money apart from the records and said plainly that nothing was lost.',
        evidence: 'Why: "The bank got Pellham’s money once, so nothing is lost; the ledger is overstated."',
      },
      {
        id: 'evidence',
        level: 'practice',
        note: 'Alex sorted the team chat’s guess as verified, and wrote that nothing was open while the A$30,000 was still to arrive.',
        evidence: 'Sort reason: "The pending list shows it is not on the statement." Unresolved risks: "None. Both parts are explained."',
      },
      {
        id: 'information',
        level: 'prompted',
        note: 'The settlement times and the duplicate check were the right first asks, but the date range took the last half hour instead of the import log, so the cause of the duplicate stayed unknown.',
        evidence: 'Requests: settlement times → duplicate check → date range. Preventive measures: "Check imports more carefully before month-end."',
      },
      {
        id: 'tradeoffs',
        level: 'prompted',
        note: 'Named who corrects the ledger and who approves it, but the control gives nobody anything specific to change.',
        evidence: 'Who owns the fix: "The finance team reverses L-5531, with the Financial Controller’s approval."',
      },
      {
        id: 'updating',
        level: 'independent',
        note: 'Moved from possible lost funds to a records problem, and said which facts moved them.',
        evidence: 'Why changed: "I started out thinking A$48,000 might be lost, because Pellham’s receipt was not on the statement…"',
      },
    ],
    feedback: {
      strength: 'You split the A$48,000 into two parts, each backed by a record, and said plainly that no money was lost.',
      improvement:
        'Explaining a part is not the same as closing it. The A$30,000 was due on 2 July, so your note should say it is expected, not settled.',
      followUp: 'How did the Pellham receipt get into the ledger twice, and what else might it have touched?',
    },
  },

  // Everything below is a DRAFT: to be confirmed, except where a comment says it comes from the source.
  goal: 'Explain what makes up the A$48,000, keep a money problem apart from a records problem, and recommend fixes and controls with owners, saying what is still unconfirmed.',
  limits: {
    deadline: 'The June month-end report is due to the Financial Controller by 1 July, 15:00',
    unacceptable: 'Reporting the gap as settled, or as lost money, without evidence; or changing the ledger without approval',
    authority:
      'You explain the difference and propose fixes and controls. Any correction to the ledger needs the Financial Controller’s approval.',
  },
  // The name and the five fields are the source's; the hints are drafted.
  submission: {
    name: 'Reconciliation Exception Note',
    fields: [
      { id: 'make-up', label: 'What makes up the difference', hint: 'Each part, with its amount' },
      { id: 'evidence', label: 'Evidence', hint: 'The record that shows each part' },
      { id: 'open-risks', label: 'Unresolved risks', hint: 'What is not yet confirmed, and what could still go wrong' },
      { id: 'fix-owner', label: 'Who owns the fix', hint: 'Who corrects what, and who approves it' },
      { id: 'prevention', label: 'Preventive measures', hint: 'What stops this happening again' },
    ],
  },
  // From the source's three Team Lead observations: a money problem kept apart from a data problem,
  // uncertainty stated accurately in the report, and follow-up controls someone can carry out; and its
  // core conflict (explaining part of the difference is not solving the whole problem).
  // ifMentions matches at the start of a word, ignoring case.
  assessment: {
    criteria: [
      {
        id: 'money-vs-records',
        label: 'Keeps a money problem apart from a records problem',
        lookFor: 'Did they say, for each part, whether money is missing or the records are wrong?',
        dimensionId: 'goal',
        ifMentions: [
          'no money',
          'not lost',
          'nothing is lost',
          'nothing lost',
          'not missing',
          'overstated',
          'records problem',
          'data problem',
          'duplicate',
          'entered twice',
          'loaded twice',
          'recorded twice',
          'imported twice',
        ],
        fields: ['make-up'],
        met: 'You said, part by part, whether money is missing or the records are wrong.',
        notYet: 'A gap can be money that never arrived or a record that is wrong. Which is each part here, and how do you know?',
      },
      {
        id: 'each-part-evidenced',
        label: 'Backs each part with a record',
        lookFor: 'Does each amount rest on a record, not on the month-end team’s guess or the team chat?',
        dimensionId: 'evidence',
        requestIds: ['r2'],
        // DRAFT: to be confirmed. Bare '2 july' became the phrases below, so '2 July' as a review date
        // doesn't count.
        ifMentions: [
          'due on 2 july',
          'due in the bank',
          'arrive on 2 july',
          'arrives on 2 july',
          'settle on 2 july',
          'settles on 2 july',
          'two business days',
          'l-5530',
          'l-5531',
          'same receipt',
          'twice',
        ],
        // DRAFT: to be confirmed. Not the initial position, a guess before the records, nor the review time ('twice a week').
        // The Examine sort reasons count ('examineReasons'): a learner may note there what the records show. r2 and the
        // evidence field are still required.
        mentionsIn: ['examineReasons', 'why', 'ownPlan', 'make-up', 'evidence', 'open-risks', 'fix-owner', 'prevention', 'mainRisk', 'owner', 'changeMind'],
        fields: ['evidence'],
        // DRAFT: to be confirmed. Ticking the month-end team's guess (c5) or the team chat (c6) under 'Based on'
        // means a part still rests on them, not on a record.
        notBasedOn: ['c5', 'c6'],
        met: 'Each part of the difference rests on a record you can point to.',
        notYet: 'The pending list shows what did not match, not why. What record shows what each part really is?',
      },
      {
        id: 'states-uncertainty',
        label: 'States what is still unconfirmed',
        lookFor: 'Does the note say the A$30,000 is expected, not received, and name what else is still open?',
        dimensionId: 'evidence',
        // DRAFT: to be confirmed. Bare 'until' became the 'until …' phrases, so 'until Friday' in a review
        // date or owner doesn't count.
        ifMentions: [
          'not yet',
          'expected',
          'due on',
          'not until',
          'until it arrives',
          'until received',
          'until confirmed',
          'unconfirmed',
          'not received',
          'still open',
          'to confirm',
          'refund',
        ],
        // DRAFT: to be confirmed. Not the owner ('Finance, to confirm') or the review time ('due on Friday'), nor the initial position,
        // where everything is still 'not yet' explained.
        mentionsIn: ['why', 'ownPlan', 'make-up', 'evidence', 'open-risks', 'fix-owner', 'prevention', 'mainRisk', 'changeMind'],
        fields: ['open-risks'],
        met: 'Your note says what is expected but not yet confirmed.',
        notYet: 'An explained part is not always a closed one. What in your note is still expected rather than confirmed?',
      },
      {
        id: 'finds-the-cause',
        label: 'Finds how the error got in, and a control that fits',
        lookFor: 'Did they find how the duplicate was made, and propose a control aimed at that cause?',
        dimensionId: 'information',
        requestIds: ['r4'],
        ifMentions: ['already loaded', 're-run', 'rerun', 'ran twice', 'run twice', 'timeout', 'timed out', 'import log', 'same row', 'same file'],
        // DRAFT: to be confirmed. Not the initial position: asking about the import log at the start is not finding the cause.
        mentionsIn: [
          'why',
          'ownPlan',
          'make-up',
          'evidence',
          'open-risks',
          'fix-owner',
          'prevention',
          'mainRisk',
          'owner',
          'reviewBy',
          'changeMind',
        ],
        met: 'You found how the duplicate got in, and aimed your control at that cause.',
        notYet: 'Knowing a record is duplicated is not knowing how. What would show the cause, so the control can stop it?',
      },
      {
        id: 'fix-with-approval',
        label: 'Proposes the fix with an owner and an approver',
        lookFor: 'Did they weigh correcting the ledger before the deadline against who must approve it, and give each fix an owner?',
        dimensionId: 'tradeoffs',
        ifMentions: ['financial controller', 'controller', 'approval', 'approve'],
        fields: ['fix-owner', 'prevention'],
        met: 'Each fix has an owner, and the correction goes to the person who must approve it.',
        notYet: 'Who may change the ledger, and who fixes the cause? Check the limits before you promise a correction.',
      },
      {
        id: 'updates-on-records',
        label: 'Updates the view on what the records showed',
        lookFor: 'Faced with the settlement times, the duplicate check or the import log, did they change or hold their first position for a stated reason?',
        dimensionId: 'updating',
        // Facts only a request reveals: 2 July and two business days (r1), L-5530/L-5531 and the
        // receipt entered twice (r2), the cut-off and no late postings (r3), the re-run and receivables
        // (r4). None is in m1–m3.
        // DRAFT: to be confirmed. Bare '2 july', '16:00' and 'cut-off' became the phrases below, so a
        // review date or time ('2 July', '16:00', 'before the cut-off') doesn't count.
        ifMentions: [
          'due on 2 july',
          'due in the bank',
          'arrive on 2 july',
          'arrives on 2 july',
          'settle on 2 july',
          'settles on 2 july',
          'two business days',
          'l-5530',
          'l-5531',
          'entered twice',
          'loaded twice',
          'recorded twice',
          'imported twice',
          're-run',
          'timeout',
          'timed out',
          'receivables',
          '36,000',
          '16:00 on 30 june',
          'stops at 16:00',
          'cut-off at 16:00',
          '16:00 cut-off',
          'between 16:00',
          "bank's cut-off",
          'bank cut-off',
          'statement cut-off',
          'posted after',
        ],
        // DRAFT: to be confirmed. The final answer shows the update, not the initial position (written before the requests), the owner or
        // the review time.
        mentionsIn: ['why', 'ownPlan', 'make-up', 'evidence', 'open-risks', 'fix-owner', 'prevention', 'mainRisk', 'changeMind'],
        met: 'Your final answer uses what the records showed, not only the first guesses.',
        notYet: 'Compare your final answer with your first position: which new facts changed it, or why did none?',
      },
    ],
    commonMisses: [
      'Explains the A$30,000 and calls the whole gap timing.',
      'Reports the unmatched receipt as lost money without checking for a duplicate.',
      'Writes that nothing is open while the card sales are still on their way.',
      'Corrects the ledger without the Financial Controller’s approval.',
      'Proposes a control too vague to act on, such as "be more careful".',
    ],
    acceptableAlternatives: [
      'Reporting the A$18,000 as not yet explained, with a duplicate as the likely cause, if the duplicate check cannot be finished by 15:00.',
      'Leaving the ledger as it is in this report and showing the duplicate as a reconciling item, if the Financial Controller cannot approve the reversal before 15:00.',
      'Escalating to a senior first, if anything looks like a real loss of money.',
    ],
    mustEscalate: [
      'Any correction to the ledger: the Financial Controller approves it.',
      'Any sign that money has really left the account or failed to arrive.',
      'Any refund or credit to Pellham Fixtures based on the receivables report.',
    ],
  },
  // The source's follow-up: a similar difference appears the next period; can last time's
  // explanation still be used? The July figures and the note are drafted.
  variant: {
    title: 'The gap comes back in July',
    changedFact:
      'July month-end: the ledger is A$30,000 higher than the bank statement. The month-end team’s note says: "Same as June: card sales on their way. Use last month’s explanation."',
    lookFor:
      'Whether the learner checks July’s own records (the settlement times, a fresh duplicate check) instead of reusing June’s explanation, since a gap of a similar size can have a different make-up; and whether they ask if the import control is live yet. The source’s question: can last time’s explanation still be used?',
  },
}
